feat: select 컴포넌트 생성
ToyVallet/swifty-bank-frontend pull request #11
Opened 2024-01-28 02:19 UTC by DoctorK4

### What is this PR?
- select 컴포넌트를 만들어 넣은 PR입니다.
---
### What has changed?
- react-select 라이브러리를 통해 구현하였습니다. 
- react-select에 커스텀 스타일을 적용하기 위해 customStyles.ts 파일을 함께 추가하였습니다.
---
### A notice to reviewers...
- 다크모드 환경에서의 테스트를 위해 page.tsx의 배경색을 변경하였습니다.
- Select 컴포넌트에서의 선택된 데이터 처리를 위해 `handleChange` 핸들러의 로직을 useState 훅과 함께 추가하여 보완할 예정입니다.
---
### Screen
<img width="421" alt="Screenshot 2024-01-28 at 10 51 06 AM" src="https://github.com/ToyVallet/swifty-frontend/assets/68728192/bd5f682d-a0de-4dc9-b905-88ea2cf8dddd">

2024-01-28 03:34 UTC, ho991217 requested changes
고생하셨습니다! 수정 후 머지부탁드려요 😎

2024-01-28 03:34 UTC, ho991217 commented on packages/ui/src/select/index.tsx
> +};
`interface`나 `type`은 파스칼 케이스로 작성하는 것이 일반적이라고 알고있습니다!
작성 해주신 다른 `interface`들과 마찬가지로 파스칼 케이스로 작성하는 것은 어떨까요?
```suggestion
interface OptionObject { 
  value: string,
  label: string 
};
```

2024-01-28 03:34 UTC, ho991217 commented on packages/ui/src/select/index.tsx
> +};
`Object`라는 이름대신 이 친구가 어떤 인터페이스인지 더 명확하게 나타내는 이름을 쓰는 것도 좋을 것 같습니다..!
```suggestion
interface Option { 
  value: string,
  label: string 
};
```
혹은 

```suggestion
interface OptionType { 
  value: string,
  label: string 
};
```
같은 이름은 어떠세요?

2024-01-28 03:34 UTC, ho991217 commented on packages/ui/src/select/index.tsx
> +  options: optionObject[] | [],
```
  options: optionObject[],
```
대신 이렇게 작성해주신 이유가 있을까요?

2024-01-28 03:34 UTC, ho991217 commented on packages/ui/src/select/index.tsx
> +  };
이 컴포넌트 외부에서 이 컴포넌트의 selectedOption에 접근하는 방법이 없는 것 같아보입니다! ;(

2024-01-28 03:34 UTC, ho991217 commented on packages/ui/src/select/index.tsx
> +      </label>
`label`은 optional prop인데, label이 없을 때에도 `<label></label>`은 랜더링될 것 같습니다

2024-01-28 03:34 UTC, ho991217 commented on packages/ui/src/select/index.tsx
아직 디자인이 확정이 아닌 것 같지만, 현재 select 컴포넌트 모습이 Input하고 구분이 안가는 것 같습니다.
디자이너님께 말씀 드리고 변경되면 바꾸면 좋을 것 같아요!

2024-01-28 03:34 UTC, ho991217 commented on packages/ui/src/select/select.css.ts
`styles`객체로 묶어서 `export default` 해 주신 것이 다른 코드들과 통일성 있어서 좋은 것 같습니다

2024-01-28 03:34 UTC, ho991217 commented on packages/ui/src/select/customStyles.ts
타입을 모두 `any`로 적어주셨는데, `any`는 지양해야 키워드라고 생각합니다. 타입을 지정할 수 없을까요?

2024-01-28 17:01 UTC, DoctorK4 commented on packages/ui/src/select/index.tsx
> +  };
그 방법을 보완하여 다시 커밋하겠습니다 ㅠ

2024-01-28 17:01 UTC, DoctorK4 commented on packages/ui/src/select/index.tsx
> +      </label>
조건부 렌더링으로 수정할게요!

2024-01-28 17:02 UTC, DoctorK4 commented on packages/ui/src/select/index.tsx
넵 확정된 디자인이 나오면 그에 따라 수정하겠습니다

2024-01-28 17:03 UTC, DoctorK4 commented on packages/ui/src/select/index.tsx
> +};
린트가 없다보니 저도 모르게 습관적으로 카멜케이스로 작성했네요 ㅠ 짚어주셔서 감사합니다. 제안해주신 식별자명으로 수정해볼게요

2024-01-29 01:36 UTC, ddaeunbb commented on packages/ui/src/select/customStyles.ts
> +const customStyles = {
객체로 정리할 생각은 못했네요. 깔끔합니다!

2024-01-29 01:36 UTC, ddaeunbb commented on packages/ui/src/select/index.tsx
> +interface SelectProps extends HTMLAttributes<HTMLDivElement>{
SelectProps가 아래에 있어서 찾게됐던 것 같아요.
`export default function Select` 컴포넌트 정의 위쪽으로 코드를 옮기는건 어떤지 한번 말씀드려봅니다.

2024-01-29 01:36 UTC, ddaeunbb commented on packages/ui/src/select/customStyles.ts
> +const customStyles = {
찾아보니 `react-select`에서 스타일을 주는 방식이 지정(?)되어있군요! 배워갑니다. 또 이렇게보니 vanilla-extract랑 잘어울리는것 같기도 하네요.

2024-01-29 03:18 UTC, ho991217 commented on packages/ui/src/select/customStyles.ts
> +const customStyles = {
그러게요 객체 단위로 관리하는게 편한 것 같습니다...!

2024-01-30 03:27 UTC, ho991217 requested changes

2024-01-30 03:27 UTC, ho991217 commented on packages/ui/src/select/index.tsx
> +        : null }
```suggestion
      { label && <label className={styles.label}>{ label }</label> }
```
와 같겠네요!

2024-01-30 03:27 UTC, ho991217 commented on packages/ui/src/select/index.tsx
>    };
요 부분 진행은 어떻게 되나요??

2024-01-30 05:13 UTC, DoctorK4 commented on packages/ui/src/select/index.tsx
> +        : null }
찾아보니 호연님이 제안해주신게 좀 더 권장되는 패턴이네요. 그렇게 수정해보도록 할게요

2024-01-30 05:14 UTC, DoctorK4 commented on packages/ui/src/select/index.tsx
>    };
이 부분 일단 기본 Select 태그로 변경해보고 제가 정보입력 페이지 구현하면서 한번 수정해봐도 될까요?

2024-01-30 05:14 UTC, DoctorK4 commented on packages/ui/src/select/index.tsx
> +interface SelectProps extends HTMLAttributes<HTMLDivElement>{
네, 인터페이스랑 타입을 컴포넌트 위쪽으로 옮기겠습니다!

2024-01-30 06:04 UTC, ho991217 commented on packages/ui/src/select/index.tsx
>    };
넵! 바텀시트가 완성되면 select 터치시 바텀시트가 열리고, 거기서 선택하는 식의 로직으로 진행해야될 것 같습니다

2024-01-30 08:36 UTC, ho991217 approved these changes

2024-01-31 03:52 UTC, ddaeunbb approved these changes

2024-01-31 04:13 UTC, merged