Button 컴포넌트 개발
ToyVallet/swifty-bank-frontend pull request #13
Opened 2024-01-29 02:33 UTC by ddaeunbb

### What is this PR?
- 버튼 컴포넌트를 만들어 넣은 PR입니다.
---
### What has changed?
- `isDisabled` 값에 따라 버튼의 스타일링이 변화합니다.
- 변화될 때 애니메이션을 추가해주었습니다.
- 버튼에 핸들러가 props로 필요합니다.
---
### A notice to reviewers...
- 버튼의 너비를 전체 너비의 `95%`로 값을 잡아두었는데, 추후 화면을 보면서 수정이 있을 것 같습니다.
- 호된 리뷰...부탁드립니다..
---
### Screen
<img width="499" alt="스크린샷 2024-01-29 오전 11 32 10" src="https://github.com/ToyVallet/swifty-frontend/assets/82816029/89e8fcd9-3d1b-4712-adf5-c2d6c4b88092">

2024-01-29 05:11 UTC, DoctorK4 approved these changes

2024-01-29 05:17 UTC, ho991217 requested changes
작은 단위의 PR 올려주신 것 좋은 것 같습니다! 고생하셨습니다.

2024-01-29 05:17 UTC, ho991217 commented on packages/ui/src/button/index.tsx
> +}
```suggestion
type ButtonVariant = "disabled" | "active";

interface ButtonProps extends HTMLAttributes<HTMLButtonElement> {
   variant: ButtonVariant;
}

export default function Button({children, className ...props}: ButtonProps) {
   // variant 따라 처리
  return (
    <button
    className={className}
    {...props}
    >{children}</button>
  )
}
```
요런 느낌은 어떠신가요?

2024-01-29 05:17 UTC, ho991217 commented on packages/ui/src/button/index.tsx
> +  children: string;
로딩 앨리먼트, 이미지, 아이콘 등이 들어갈 수 있도록 하기위해서는 `string`타입 보다는 `React.ReactNode`타입이 더 적절해보입니다!

2024-01-29 05:17 UTC, ho991217 commented on packages/ui/src/button/index.tsx
> +  handleClick: () => void;
핸들러 외부로 빼 주신 부분 좋았던 것 같습니다! 다만, `handle~`이라는 prefix는 이벤트를 다루는 함수에 붙으면 더 적절할 것 같습니다!

2024-01-29 05:17 UTC, ho991217 commented on packages/ui/src/button/index.tsx
ConfirmButton을 따로 만들기보다, 일반적인 Button 컴포넌트를 먼저 만들고, variant 등으로 구분하는 것은 어떨까요?

2024-01-29 05:17 UTC, ho991217 commented on packages/ui/src/button/button.css.ts
> +const able= style({
변수 네임이 `base` 여도 될 것 같습니다.

2024-01-29 07:36 UTC, ddaeunbb commented on packages/ui/src/button/index.tsx
variant로 구분해 if문이나 switch문을 사용해서 다른 jsx를 리턴하게 할까 고민했는데, 생각해보니 하나의 버튼이여야하고 양식을 모두 입력하거나하는 조건이 모두 만족되면 `disabled`가 해제되어야해서 하나의 `element`로 사용해 수정하였습니다.🥲

2024-01-29 08:22 UTC, ho991217 commented on packages/ui/src/button/index.tsx
다른 jsx여야 할 이유가 있나요?? 결국은 스타일이나 동작만 다른 `<button />`아닌가용??

2024-01-30 05:27 UTC, ddaeunbb commented on packages/ui/src/button/index.tsx
애니메이션 고려해서 하나 버튼태그로 둔거긴합니다ㅠ 뭔가 입력양식에대한 조건이 모두 만족되면 버튼색이 돌아오는 모션을 넣는게 맞지 않을까 고려해서요 ㅠㅜ

2024-01-30 14:48 UTC, merged