feat: signin/form 페이지 구현 (진행중)
ToyVallet/swifty-bank-frontend pull request #22
Opened 2024-02-06 14:31 UTC by DoctorK4

### What is this PR?
- 
---
### What has changed?
- 
---
### A notice to reviewers...
- 
---
### Screen

2024-02-20 06:16 UTC, kd02109 reviewed
정말 고생 많이 하셨어요! 확실히 input 관련 form을 사용하는 경우 validation과 더불어 고려해 할 점이 많다는 것을 느꼈습니다. 

현재 validation을 통과 하지 못했을 때, error를 보여주는 방법과, 회원가입 시 주민등록번호가 올바르지 않거나. 전화번호가 올바르지 않는 경우를 해당 방법으로는 모두 확인을 할 수 없으니, 이를 서버 쪽과 이야기해서 어떻게 처리할지 생각해봐야 할 것 같아요!

2024-02-20 06:16 UTC, kd02109 commented on packages/hooks/src/useInput.ts
> +  };
custom hook에서 함수를 반환하는 경우 렌더링 최적화를 고려해서 useCallback을 한번 씌우는 건 어떨까요? 해당 훅을 사용해서 자식 컴포넌트에 내려 줄 때, 불필요한 리렌더링이 있을 수도 있을 것 같아서 여쭤봅니다!

2024-02-20 06:16 UTC, kd02109 commented on packages/ui/src/select/index.tsx
> +      </BottomSheet>
Select 컴포넌트가 항상 BottomSheet에 종속적으로 사용되는지 여쭤보고 싶어요!
공통 컴포넌트의 경우 분리해서 관리하고 사용이 필요한 페이지에서 컴포넌트로 따로 만들어서 관리하는 건 어떨까요?

2024-02-20 06:16 UTC, kd02109 commented on apps/swifty-bank/app/signin/form/page.tsx
> +        </motion.div>
해당 부분 디자인을 확인했을 때 idInputBlind의 배치가 깨지는 것 같아요!
<img width="184" alt="phone_form_style" src="https://github.com/ToyVallet/swifty-frontend/assets/57277708/81223bf5-7925-44d9-b450-e88d9ea94356">

2024-02-20 06:16 UTC, kd02109 commented on apps/swifty-bank/app/signin/form/page.tsx
> +  const username = useInput("");
공통 UI로 사용되는 Input component는 useRef 사용을 고려해서 만든 것 같다고 생각했습니다. 이때 해당 페이지에서 state로 관리하는 이유가 있을까요?

2024-02-20 06:16 UTC, kd02109 commented on apps/swifty-bank/app/signin/form/page.tsx
> +  };
../_lib/validate/isActiveButton.ts 에 정의한 interface FormData임을 명시해주는게 파악할때 더 빠를 것 같아요!

2024-02-20 06:16 UTC, kd02109 commented on apps/swifty-bank/app/signin/form/page.tsx
> +            }
return 하는 반환 값 내부에 직접 함수를 작성하는 것 보다는 명시적으로 함수를 선언하고 prop으로 내려주는 것이 렌더링 할 때 이점이 더 있을 것 같아요! 저는 개인적으로 prop으로 내려주는 함수 경우 useCallback으로 감싸서 최대한 리렌더링을 줄이려고 하는데, 어떻게 생각하시나요?

2024-02-20 06:16 UTC, kd02109 commented on apps/swifty-bank/app/signin/form/page.tsx
> +            type="submit"
이 부분에서 다음과 같은 타입 에러가 발생하는데 Button 컴포넌트는 디자인과 사용 방법에 맞추어 한번 수정을 해야겠네요 ㅜㅜㅜ 

```
Type '{ children: string; variant: "active" | "disabled"; type: string; }' is not assignable to type 'IntrinsicAttributes & ButtonProps'.
  Property 'type' does not exist on type 'IntrinsicAttributes & ButtonProps'.
```

2024-02-20 08:13 UTC, DoctorK4 commented on packages/hooks/src/useInput.ts
> +  };
> custom hook에서 함수를 반환하는 경우 렌더링 최적화를 고려해서 useCallback을 한번 씌우는 건 어떨까요? 해당 훅을 사용해서 자식 컴포넌트에 내려 줄 때, 불필요한 리렌더링이 있을 수도 있을 것 같아서 여쭤봅니다!

놓친 부분을 잘 얘기해주신 것 같습니다! 반영하도록 하겠습니다.

2024-02-20 08:25 UTC, DoctorK4 commented on packages/ui/src/select/index.tsx
> +      </BottomSheet>
네, Select에서 BottomSheet가 종속적으로 사용됩니다.
그래서 공통 컴포넌트의 Select를 아예 수정을 한 부분입니다. 
같은 @swifty/ui안에서 종속성을 갖는게 안좋다고 보시는걸까요?

2024-02-20 08:28 UTC, DoctorK4 commented on apps/swifty-bank/app/signin/form/page.tsx
> +            type="submit"
> 이 부분에서 다음과 같은 타입 에러가 발생하는데 Button 컴포넌트는 디자인과 사용 방법에 맞추어 한번 수정을 해야겠네요 ㅜㅜㅜ
> 
> ```
> Type '{ children: string; variant: "active" | "disabled"; type: string; }' is not assignable to type 'IntrinsicAttributes & ButtonProps'.
>   Property 'type' does not exist on type 'IntrinsicAttributes & ButtonProps'.
> ```

넵, 타입에러는 인지하였습니다만, 현재 브랜치에서 수정하기 보다는 공통 컴포넌트를 수정하는 부분에서 별개로 처리해야할 task일 것 같아서 일단은 구현에 우선순위를 두고 TODO 주석으로 남겨두었습니다.

2024-02-20 08:36 UTC, DoctorK4 commented
> 정말 고생 많이 하셨어요! 확실히 input 관련 form을 사용하는 경우 validation과 더불어 고려해 할 점이 많다는 것을 느꼈습니다.
> 
> 현재 validation을 통과 하지 못했을 때, error를 보여주는 방법과, 회원가입 시 주민등록번호가 올바르지 않거나. 전화번호가 올바르지 않는 경우를 해당 방법으로는 모두 확인을 할 수 없으니, 이를 서버 쪽과 이야기해서 어떻게 처리할지 생각해봐야 할 것 같아요!

네, 저도 그 부분이 고민이었는데요
이름과 맞는 주민번호나 전화번호를 검증하는 것은 외부 본인인증 API를 쓰지 않는 이상 정확하게는 특정하기 어렵지 않을까 싶습니다.
미국 번호를 사용하는 부분이 있어 전화번호까지는 아니더라도,
주민번호의 월(1~12월), 일(1~31일)에 대한 검증은 추후에 자체적으로라도 구체화할 수 있는 부분인 것 같습니다.

2024-02-20 09:11 UTC, DoctorK4 commented on apps/swifty-bank/app/signin/form/page.tsx
> +        </motion.div>
수정하였습니다 감사합니다!

2024-02-20 10:15 UTC, kd02109 commented on packages/ui/src/select/index.tsx
> +      </BottomSheet>
지금 당장의 디자인에서는 문제가 없다고 생각하는데, 해당 공통 컴포넌트를 계속 확장해서 사용해야 하는 측면에서 사용 방법이 제한 적인 것 같아서 이후에 다른 디자인의 수정이 있거나, 다른 방식으로 select를 제공해야 하면, 확장성에 문제가 있을 것 같아서 여쭤봤어요!

2024-02-20 10:27 UTC, ho991217 requested changes
많은 양 정말 고생 많으셨습니다! 읽어보시고 궁금한 점 있으시면 말씀해주세요!

2024-02-20 10:27 UTC, ho991217 commented on apps/swifty-bank/app/signin/form/page.css.ts
퍼블리싱이 디자인과 차이가 있는 것 같아요!
혹시 모바일 기기로도 디버깅 해보셨나요?

2024-02-20 10:27 UTC, ho991217 commented on apps/swifty-bank/app/signin/form/page.tsx
폼을 채우고 뒤로 가기를 눌렀다가 다시 원래 페이지로 돌아오면 폼이 채워져 있는데도 `다음`버튼이 눌리지 않는 버그가 있네요!!

2024-02-20 10:27 UTC, ho991217 commented on apps/swifty-bank/app/signin/_lib/constants/tsp.ts
이런 객체의 경우 재사용 가능성이 높아서 따로 타입으로 지정해서 빼 주어도 좋을 것 같습니다!
```ts
type SelectType<T> = {
  label: string;
  value: T;
}
```

2024-02-20 10:27 UTC, ho991217 commented on apps/swifty-bank/app/signin/_lib/validate/validateID.ts
> +  if (isNaN(Number(back))) return false;
`isNaN`은 매개변수를 `number`로 강제 타입캐스팅 후 검사를 진행합니다!
따라서 Number로의 타입캐스팅은 불필요합니다!
```suggestion
  if (isNaN(front)) return false;

  if (isNaN(back)) return false;
```

2024-02-20 10:27 UTC, ho991217 commented on apps/swifty-bank/app/signin/form/page.tsx
> +              </Input>
![image](https://github.com/ToyVallet/swifty-frontend/assets/84632077/5916dedb-48fe-4c27-8e41-83635bc4b850)

`number`로 캐스팅 하다보니 음수가 가능하네요..

2024-02-20 10:27 UTC, ho991217 commented on apps/swifty-bank/app/signin/form/page.tsx
> +        </div>
unmount가 아니라 가려주고 있기때문에, 모든 요소가 한번에 다 존재하네요

![image](https://github.com/ToyVallet/swifty-frontend/assets/84632077/518fce0c-864d-4cb7-8404-0c2ff77241d4)

2024-02-20 10:27 UTC, ho991217 commented on apps/swifty-bank/app/signin/form/page.tsx
가입은 signup인데 전체적으로 네이밍이 signin으로 되어있네요!

2024-02-20 10:27 UTC, ho991217 commented on apps/swifty-bank/app/signin/form/page.tsx
> +          animate={{ opacity: signinStage >= 2 ? 1 : 0 }}
애니메이션이 단순 opacity 변화 뿐인데, framer대신 순수 css로도 가능한 내용 같아요!
위치 이동이라던가, exit animation 등이 있다면 유용하겠네요!

2024-02-20 10:27 UTC, ho991217 commented on apps/swifty-bank/app/signin/_lib/validate/validateID.ts
문자열 검사와 정규식 검사를 활용하는 것은 어떨까요?

2024-02-20 10:27 UTC, ho991217 commented on apps/swifty-bank/app/signin/form/page.tsx
> +        </div>
```js
const signinStep = ['휴대폰 번호', '통신사', '주민등록번호 앞 7자리', '이름'];
```
로 사용하면
```js
{signinStep}를 알려주세요
```
로 매핑할 수 있겠네요!

2024-02-20 10:27 UTC, ho991217 commented on apps/swifty-bank/app/signin/form/page.tsx
`react-hook-form`을 이용하면 더 쉽게 폼을 관리할 수 있을 것 같아요!

2024-02-20 10:27 UTC, ho991217 commented on apps/swifty-bank/app/signin/form/page.tsx
> +              <span className={styles.idInputBlind}>······</span>
디자인과 차이가 있는 것 같아요!

2024-02-20 10:27 UTC, ho991217 commented on apps/swifty-bank/app/signin/form/page.tsx
> +          transition={{ duration: 1 }} // 애니메이션 지속 시간 설정
공통되는 값들은 따로 관리하면 좋을 것 같습니다!

2024-02-20 10:27 UTC, ho991217 commented on apps/swifty-bank/app/signin/form/page.tsx
> +          </Input>
숫자를 제외하고도 모든 문자가 입력되네요!

2024-02-20 10:27 UTC, ho991217 commented on apps/swifty-bank/app/signin/form/page.tsx
> +          </Input>
모바일 기기에서 디버깅을 해보면, tel 패드가 아니라 일반 키보드가 뜨는데요,
숫자 패드를 띄워 유저로 하여금 전화번호를 입력해주는 필드라는 것을 알려줘야한다고 생각합니다.

2024-02-20 10:27 UTC, ho991217 commented on apps/swifty-bank/app/signin/form/page.tsx
> +            type="submit"
버튼이 옆으로 튀어 나가네요...ㅠㅠ

2024-02-20 10:27 UTC, ho991217 commented on packages/hooks/src/useInput.ts
> +};
리턴 타입을 이렇게 명시해주지 않아도 추론이 가능하지 않나요?

2024-02-20 10:27 UTC, ho991217 commented on packages/ui/src/input/index.tsx
> +  const generatedId = useId();
prefix를 따로 제거해주신 이유가 있나요?

2024-02-20 10:27 UTC, ho991217 commented on packages/ui/src/select/index.tsx
> +        expandTo="1/3"
`expandTo` 는 왜 지정 해 주셨나요?

2024-02-20 10:27 UTC, ho991217 commented on packages/ui/src/select/index.tsx
> +    inputRef.current?.blur();
바텀시트가 닫히면 꼼꼼하게 blur 처리 해주시는 것 좋은 것 같습니다!

2024-02-20 10:27 UTC, ho991217 commented on packages/ui/src/select/index.tsx
> +  const handleDismiss = () => {
어떠한 이벤트도 다루지 않는 함수는 `onDismiss`라는 이름이 더 적합하지 않을까요?

2024-02-20 10:27 UTC, ho991217 commented on packages/ui/src/select/index.tsx
> +  };
`handleClick`이라는 함수지만 마우스이벤트와 키보드이벤트를 동시에 다루고 있습니다..!
함수의 의도와는 맞지 않는 것 같아요!

2024-02-20 10:27 UTC, ho991217 commented on packages/ui/src/select/index.tsx
> +      | React.KeyboardEvent<HTMLButtonElement>,
마우스와 키보드 이벤트를 다루고 있지만, 저희 서비스는 오직 터치만을 이용해서 동작합니다!
이 부분에 대한 고려가 필요할 것 같아요.
https://ui.toast.com/posts/ko_20220106

2024-02-20 10:27 UTC, ho991217 commented on packages/ui/src/select/index.tsx
> +    const target = e.target as HTMLButtonElement;
type assertion은 왜 해주시는건가요?

2024-02-20 10:27 UTC, ho991217 commented on packages/ui/src/select/select.css.ts
> +  fontSize: "1.063rem",
`1.063rem`이라는 사이즈는 뭔가요..?!?!

2024-02-20 10:27 UTC, ho991217 commented on packages/ui/src/select/index.tsx
> +  onChange?: (event: React.ChangeEvent<HTMLInputElement>) => void;
위에서 말씀 드린 SelectType을 만들어두면
```suggestion
className?: string;
options: SelectType[];
```
이렇게 줄일 수 있지 않을까요?

2024-02-20 10:27 UTC, ho991217 commented on apps/swifty-bank/app/signin/form/page.tsx
> +  const [signinStage, setSigninStage] = useState<SigninStage>(0);
위에서 말씀드린 것 처럼, 각 단계를 배열로 관리해도 좋아보여요!

2024-02-20 10:27 UTC, ho991217 commented on apps/swifty-bank/app/signin/_lib/validate/isActiveButton.ts
> +import validatePN from "./validatePN";
이 두 함수는 한 파일에 있어도 되지 않을까요?!

2024-02-20 10:27 UTC, ho991217 commented on apps/swifty-bank/app/signin/_lib/validate/isActiveButton.ts
> +  signinStage: SigninStage,
type SignupStage = '휴대폰 번호' | '통신사' | '주민등록번호 앞 7자리' | '이름';
이라면 더 코드에 의미가 명확히 보일 것 같아요!

2024-02-20 10:27 UTC, ho991217 commented on apps/swifty-bank/app/signin/_lib/validate/isActiveButton.ts
> +  }
만약 이렇게 인덱스 넘버로 작성하실 거라면, validator array를 만들어서 매핑을 해도 좋을 것 같아요

2024-02-20 10:27 UTC, ho991217 commented on apps/swifty-bank/app/signin/_lib/validate/isActiveButton.ts
> +): boolean => {
return type assertion이 되지 않나요?

2024-02-26 09:19 UTC, DoctorK4 commented on apps/swifty-bank/app/signin/_lib/validate/isActiveButton.ts
> +  signinStage: SigninStage,
enum을 사용하여 반영하였습니다.

2024-02-26 09:19 UTC, DoctorK4 commented on packages/ui/src/select/index.tsx
> +  const handleDismiss = () => {
논의한대로의 컨벤션으로 변경하였습니다!

2024-02-26 09:19 UTC, DoctorK4 commented on apps/swifty-bank/app/signin/form/page.tsx
> +        </div>
하나의 태그에서 동적으로 내용을 변경하는 식으로 반영하였습니다.

2024-02-26 09:19 UTC, DoctorK4 commented on packages/hooks/src/useInput.ts
> +};
그렇네요 굳이 적어주지 않아도 될 부분인 것 같아서 삭제하여 반영하였습니다.

2024-02-26 09:19 UTC, DoctorK4 commented on packages/ui/src/select/select.css.ts
> +  fontSize: "1.063rem",
17px을 px to rem을 통해 계산한 값을 넣었습니다.

2024-02-26 09:19 UTC, DoctorK4 commented on packages/ui/src/select/index.tsx
> +        expandTo="1/3"
지정 필요한 속성값인줄 알고 지정했습니다. 불필요한 지정이므로 삭제하겠습니다.

2024-02-26 09:19 UTC, DoctorK4 commented on packages/ui/src/input/index.tsx
> +  const generatedId = useId();
아 처음에 최상단 훅사용 관련 버그가 나서 @swifty/hooks를 임시로 주석처리하고, react 내장 useId로 사용하였습니다.
지금은 다시 이상없이 렌더링돼서, 원복해두었습니다!

2024-02-26 09:19 UTC, DoctorK4 commented on apps/swifty-bank/app/signin/form/page.tsx
> +              </Input>
정규식을 통해 보완하였습니다

2024-02-26 09:19 UTC, DoctorK4 commented on apps/swifty-bank/app/signin/form/page.tsx
> +              <span className={styles.idInputBlind}>······</span>
Blind 부분 말씀하시는걸까요? SVG로 변경하여 디자인과 싱크를 맞췄습니다.

2024-02-26 09:19 UTC, DoctorK4 commented on apps/swifty-bank/app/signin/form/page.tsx
> +          </Input>
키패드를 제가 생각못했네요. inputMode 속성으로 tel을 추가해주었습니다!

2024-02-26 09:19 UTC, DoctorK4 commented on apps/swifty-bank/app/signin/form/page.tsx
> +  const username = useInput("");
우선, 공통 Input의 특징을 잘 고려하지 못했던 것 같습니다.
그리고 하단 버튼의 active 여부와 validation 결과를 연동하려면 state가 더 좋지 않을까 생각했습니다.

2024-02-26 09:19 UTC, DoctorK4 commented on apps/swifty-bank/app/signin/form/page.tsx
defaultValue 지정하여 폼이 채워져있는 것을 초기화하였습니다. 디테일하게 리뷰해주신 덕에 고쳤네요 👍🏼

2024-02-26 09:19 UTC, DoctorK4 commented on apps/swifty-bank/app/signin/form/page.tsx
> +          animate={{ opacity: signinStage >= 2 ? 1 : 0 }}
exit animation을 추가하였습니다. 이후에 리팩토링하면서 더 추가할만한 애니메이션이 있을지 검토해보겠습니다

2024-02-26 09:19 UTC, DoctorK4 commented on apps/swifty-bank/app/signin/form/page.tsx
> +          </Input>
hook-form 적용해보면서 막아보겠습니다...!

2024-02-26 09:19 UTC, DoctorK4 commented on apps/swifty-bank/app/signin/_lib/validate/validateID.ts
제안해주신대로 정규표현식 사용하는 것이 엣지케이스도 덜 만들고 코드도 깔끔해져서 그렇게 수정하였습니다.

2024-02-26 09:19 UTC, DoctorK4 commented on apps/swifty-bank/app/signin/form/page.tsx
적용 한번 해보겠습니다...!

2024-02-26 09:19 UTC, DoctorK4 commented on packages/ui/src/select/index.tsx
> +    const target = e.target as HTMLButtonElement;
e.target을 사용하다보니 타입 경고를 피하기 위해 assertion을 했습니다. 
리뷰 이후에 스스로도 assertion 지양하고자 type narrowing과 currentTarget으로 바꾸어서 다시 커밋하였습니다.

2024-02-26 09:19 UTC, DoctorK4 commented on packages/ui/src/select/index.tsx
> +  };
뭔가 키보드로도 접근가능해야할 것 같아서 추가했는데 그게 되려 불필요한 코드가 되었군요 ㅠ 클릭이벤트만 처리하도록 하였습니다.

2024-02-27 11:26 UTC, kd02109 commented on apps/swifty-bank/app/signup/form/page.tsx
>                />
해당 부분에서 idFront에서 생년월일 6자리가 모두 입력되고 난후에 자동으로 idBack에 focus가 되면 좋을 것 같아요!
useEffect와 ref를 활용하면 처리할 수 있을 것 같아요. 생각보다 주민등록번호 앞자리 입력후 뒷자리 입력하기 위해 터치하는데 불편하더라고요!

2024-02-27 11:27 UTC, kd02109 approved these changes

2024-02-27 11:31 UTC, kd02109 reviewed
고생하셨습니다!! 

자잘한 스타일과 편의성 이외에는 저는 문제가 없는 것 같아요!

2024-02-27 11:31 UTC, kd02109 commented on apps/swifty-bank/app/signup/form/page.tsx
> +export default SignupForm;
![image](https://github.com/ToyVallet/swifty-frontend/assets/57277708/39f87ad8-e592-4b57-b1d3-8419989cbdc1)

테스트 했을 때 라벨이 피그마 디자인과 동일하게 적용이 되지 않은 것 같아요!

2024-02-27 14:00 UTC, ho991217 approved these changes
LGTM

2024-02-27 14:00 UTC, merged