회원가입 약관 동의, 약관 상세
ToyVallet/swifty-bank-frontend pull request #25
Opened 2024-02-12 09:55 UTC by kd02109

### What is this PR?
- 회원 가입 약관 동의 페이지 구현
- 회원 가입 약관 동의 상세 설명 페이지 구현
---
### What has changed?

- 우선 기본 화면 구성에 집중했습니다. 

**약관동의**
  - /agreement url 주소에 약관 동의 페이지 화면을 만들었습니다.
  - 아직 button 컴포넌트 디자인 수정이 안되어 있어서 기존 컴포넌트를 활용했습니다. 
  - BottomSheet가 구현이 안되어 있기 때문에, 차후 활용하는 것을 가정해서 client component로 분리하여 두었습니다.

**약관 동의 상세**
   - /agreement/detail url 주소에 페이지를 구현했습니다. 
   - X 버튼을 클릭하면 /agreement url로 가도록 했습니다. 
   - 해당 페이지 이동을 고려한다면, 약관동의 여부를 context 혹은 상태 공유 api를 통해 관리 해야 할 것 같습니다. 
---
### A notice to reviewers...
- 
---
### Screen
- agreement

<img width="148" alt="agreement" src="https://github.com/ToyVallet/swifty-frontend/assets/57277708/f8769123-1f25-4cca-85a4-9e69a06de9f6">

- detail

<img width="148" alt="detail" src="https://github.com/ToyVallet/swifty-frontend/assets/57277708/6488765f-24cf-4cb7-a1c0-54da7cc9ffa5">

2024-02-12 10:52 UTC, ho991217 requested changes
고생하셨습니다 🔥
이것 저것 달다보니 리뷰가 18개가 되어버렸네요...!
활발한 의견 공유 있었으면 좋겠습니다!

2024-02-12 10:52 UTC, ho991217 commented on apps/swifty-bank/public/img/agreement/Symbol_Agree.png
이미지 사이즈가 더 커야할 것 같아요! 깨지네요

2024-02-12 10:52 UTC, ho991217 commented on apps/swifty-bank/public/img/agreement/Icon_Cancellation.svg
이 아이콘은 전역적으로 많이 사용하게될 것 같은데, cross 정도의 이름으로 공통 폴더에 두어서 재사용성을 높이는건 어떤가요?

2024-02-12 10:52 UTC, ho991217 commented on apps/swifty-bank/app/agreement/_component/AgreementBtn.tsx
이렇게 따로 정의해주신 이유가 있을까요?

2024-02-12 10:52 UTC, ho991217 commented on apps/swifty-bank/app/agreement/detail/page.tsx
```shell
Uncaught ModuleBuildError: Module build failed (from ../../node_modules/@vanilla-extract/webpack-plugin/loader/dist/vanilla-extract-webpack-plugin-loader.cjs.js):
NonErrorEmittedError: (Emitted value instead of an instance of Error) ReferenceError: $RefreshReg$ is not defined
```
라는 에러가 뜨면서 접근이 안되네요

2024-02-12 10:52 UTC, ho991217 commented on apps/swifty-bank/app/agreement/detail/page.css.ts
> +});
as-is는
```suggestion
const container = style({
  width: "100%",
  height: "100%",
  fontSize: 16,
  display: "flex",
  flexDirection: "column",
  gap: vars.space[4],
});

const header = style({
  paddingBottom: `${vars.space[3]}`,
  borderBottom: `3px solid ${vars.color.gray[300]}`,
});

const content = style({
  marginTop: vars.space[1],
});

const list = style({
  listStyle: "none",
  display: "flex",
  flexDirection: "column",
  gap: vars.space[5],
});

const listContent = style({
  display: "inline-block",
  marginTop: vars.space[1],
});

const listDetail = style({
  display: "inline-block",
});

const styles = {
  container,
  header,
  content,
  list,
  listContent,
  listDetail
};
```
의 형태로 작성하는 것을 컨벤션으로 하고 있습니다!

2024-02-12 10:52 UTC, ho991217 commented on apps/swifty-bank/app/agreement/detail/page.tsx
> +} from "./page.css";
styles라는 객체로 묶어서 내보내주게 되면
여기서 나온 header, list 등 generic한 단어들을 사용할 때, 재선언의 위험이 줄어들게 됩니다!
```suggestion
import styles from "./page.css";
```
이렇게 `import` 하고

```tsx
<li className={styles.list}>리스트</li>
```
위와 같이 쓸 수 있겠죠!
추후 한 페이지에 많은 스타일이 포함될 때 유용한 방식이라고 생각합니다

2024-02-12 10:52 UTC, ho991217 commented on apps/swifty-bank/app/agreement/detail/page.css.ts
> +  paddingBottom: `${vars.space[3]}`,
```ts
paddingBottom: vars.space[3],
```
대신 이렇게 써 주신 이유가 있나요?

2024-02-12 10:52 UTC, ho991217 commented on apps/swifty-bank/app/agreement/detail/_component/BackBtn.tsx
> +    </button>
`<Link></LInk>`컴포넌트 대신 button을 이용하신 이유가 있나요?

2024-02-12 10:52 UTC, ho991217 commented on apps/swifty-bank/app/agreement/detail/_component/BackBtn.tsx
> +  };
`on` prefix와 `handle`prefix를 비교해보았을 때, `handle`이라는 prefix는 이벤트를 핸들링하는 함수에 더 적합해보입니다.
인자로 이벤트를 받아와서 활용하는 함수에서는 `handle...`, 그렇지 않은 함수에서는 `on...`을 활용해보는건 어떨까요?

2024-02-12 10:52 UTC, ho991217 commented on apps/swifty-bank/app/agreement/detail/_component/BackBtn.tsx
> +export default function BackBtn() {
기존 버튼 컴포넌트의 이름은 `Button`으로 되어있습니다.
`BackButton`과 `BackBtn` 중 어떤것이 더 통일성있는 이름인지 고민해보면 좋을 것 같습니다.

2024-02-12 10:52 UTC, ho991217 commented on apps/swifty-bank/app/agreement/detail/page.tsx
> +};
타입을 지정해주신 것 것이 좋네요!
`Info`라는 너무 일반적인 단어보다는
`TermsOfService`, `ToS`, `TermsAndConditions`, `TermsOfUse`
등을 고려해보면 좋을 것 같아요!

2024-02-12 10:52 UTC, ho991217 commented on apps/swifty-bank/app/agreement/detail/page.tsx
> +            </li>
이 부분도 컴포넌트화할 수 있지 않을까요?

2024-02-12 10:52 UTC, ho991217 commented on apps/swifty-bank/app/agreement/page.css.ts
마찬가지로 `styles`객체로 모듈화하면 좋을 것 같아요!

2024-02-12 10:52 UTC, ho991217 commented on apps/swifty-bank/app/agreement/page.tsx
> +        <div className={imgCircle}></div>
empty element는 self-closing 하도록 작성해주세요!

2024-02-12 10:52 UTC, ho991217 commented on apps/swifty-bank/app/agreement/page.tsx
> +export default function AgreementPage() {
사이 들여쓰기가 필요해보입니다!

2024-02-12 10:52 UTC, ho991217 commented on apps/swifty-bank/app/agreement/page.tsx
> +        <span className={explain}>설명 및 약관을 이해하였음을 확인합니다.</span>
이 친구도 Heading의 일종 아닐까요?

2024-02-12 10:52 UTC, ho991217 commented on apps/swifty-bank/app/agreement/page.tsx
> +        <Heading type="h2">약관에 동의 해주세요</Heading>
한 문장이지만 길이가 길기 때문에 두 줄로 분리가 된 케이스인데요! 각각의 heading으로 감싸는게 맞을까요? 아니면 작성해주신 것처럼 두개로 나누어서 감싸는 것이 좋을까요?

2024-02-12 10:52 UTC, ho991217 commented on apps/swifty-bank/app/agreement/page.css.ts
> +});
`backdrop`, `imgBg`, `imgBackdrop` 등 단순히 circle보다 이 스타일을 설명할 수 있는 더 다양한 표현이 있을 것 같아요!

2024-02-12 10:56 UTC, kd02109 commented on apps/swifty-bank/app/agreement/_component/AgreementBtn.tsx
해당 컴포넌트는 서버 컴포넌트가 아닌 클라이언트 컴포넌트로 클릭 이벤트와 react state를 활용해야 할 것 같아서 별도의 컴포넌트로 분리했습니다.

2024-02-12 10:58 UTC, kd02109 commented on apps/swifty-bank/app/agreement/page.tsx
> +        <Heading type="h2">약관에 동의 해주세요</Heading>
이 부분은 저도 작성을 하면서 고민했습니다. width %를 좁게 하고 하나의 Heading 컴포넌트로 관리할 수 있지만, 각 디바이스의 width 별로 해당 문구 형식을 일괄적으로 똑같이 보여줄 수 없을 것 같아서 두개의 Heading으로 나눴습니다.

2024-02-12 10:59 UTC, kd02109 commented on apps/swifty-bank/app/agreement/page.tsx
> +        <span className={explain}>설명 및 약관을 이해하였음을 확인합니다.</span>
설명 및 약관이 Heading 스타일과 맞지 않고 일반적인 text 형식으로 작성되어 있어서 Heading 보다는 span을 사용했습니다.

2024-02-12 11:09 UTC, kd02109 commented on apps/swifty-bank/public/img/agreement/Icon_Cancellation.svg
좋은 방법인것 같습니다. 그러면 icon은 여러 곳에서 반복 사용할 수 있으니 public/icon 경로에 저장하는데 어떨까요? 이렇게 svg 파일 관리하는게 더 직관적일 것 같아요

2024-02-12 11:18 UTC, kd02109 commented on apps/swifty-bank/app/agreement/detail/page.tsx
어 저는 해당 문제 없이 dev 환경에서 실행이 되는데, 빌드시에 발생된 에러인가요?

2024-02-12 11:27 UTC, kd02109 commented on apps/swifty-bank/app/agreement/detail/page.css.ts
> +  paddingBottom: `${vars.space[3]}`,
이부분은 제가 놓쳤네요! 크게 이유가 없습니다. 작성 방식 통일 하도록 할게요!

2024-02-12 11:28 UTC, kd02109 commented on apps/swifty-bank/app/agreement/detail/_component/BackBtn.tsx
> +    </button>
링크 컴포넌트의 존재를 잊었습니다! ! 수정 하겠습니다!

2024-02-12 11:36 UTC, kd02109 commented on apps/swifty-bank/app/agreement/detail/page.tsx
> +            </li>
이부분 컴포넌트화도 생각해보았는데, 해당 형식의 약관이 재사용되지 않는점, 해당 pgae에서 컴포넌트로 분리해서 가독성을 해치는 것 보다는 하나의 파일에서 관리하는게 후에 코드를 읽을 때 편할 것 같아서 굳이 분리하지 않았습니다.

2024-02-12 11:47 UTC, ho991217 commented on apps/swifty-bank/public/img/agreement/Icon_Cancellation.svg
좋습니다!

2024-02-12 11:47 UTC, ho991217 commented on apps/swifty-bank/app/agreement/detail/page.tsx
아뇨 dev 모드로 실행후 /agreement/detail 접근하면 발생합니다

2024-02-12 11:57 UTC, kd02109 commented
해당 review 반영해서 수정해야 하는 부분 수정했습니다!

2024-02-12 11:59 UTC, kd02109 commented
url 경로를 하나의 object로 관리하면 좋을 것 같은데 /app/_lib 폴더를 만들고 하나의 파일에서 관리를 하려고 합니다. path.ts로 파일을 만들어서 path 변수에서 관리하는게 어떨까요? 추가 path가 있을 때 마다 path 변수에 url을 추가하면서 관리하면 좋을 것 같습니다.!

2024-02-12 14:39 UTC, DoctorK4 commented on apps/swifty-bank/app/agreement/detail/page.tsx
저도 /agreement/detail 엔드포인트에서 접근이 안됩니다.

2024-02-12 14:49 UTC, DoctorK4 commented
> url 경로를 하나의 object로 관리하면 좋을 것 같은데 /app/_lib 폴더를 만들고 하나의 파일에서 관리를 하려고 합니다. path.ts로 파일을 만들어서 path 변수에서 관리하는게 어떨까요? 추가 path가 있을 때 마다 path 변수에 url을 추가하면서 관리하면 좋을 것 같습니다.!

좋습니다!

2024-02-13 03:57 UTC, ho991217 commented
> url 경로를 하나의 object로 관리하면 좋을 것 같은데 /app/_lib 폴더를 만들고 하나의 파일에서 관리를 하려고 합니다. path.ts로 파일을 만들어서 path 변수에서 관리하는게 어떨까요? 추가 path가 있을 때 마다 path 변수에 url을 추가하면서 관리하면 좋을 것 같습니다.!

이름은 _lib이 적당할까용? 상수라는 의미로 `/constants/path.ts` 도 좋을 것 같구요

2024-02-13 04:04 UTC, ho991217 requested changes

2024-02-13 04:04 UTC, ho991217 commented on apps/swifty-bank/app/agreement/_component/agreementBtn.css.ts
> +};
이 부분은 다같이 통일해야 할 것 같네요! 지금은 어디에서는 export default가 되고 있고, 서로 다르네용

2024-02-13 04:04 UTC, ho991217 commented on apps/swifty-bank/app/agreement/detail/page.tsx
여전히 안되네요 ;(

2024-02-13 04:04 UTC, ho991217 commented on apps/swifty-bank/public/img/agreement/Symbol_Agree.webp
webp가 깨지는 것 같아요!
<img width="644" alt="스크린샷 2024-02-13 13 04 12" src="https://github.com/ToyVallet/swifty-frontend/assets/84632077/04a0a48a-2472-4955-bcf5-a1fce3d4b110">

2024-02-13 05:18 UTC, kd02109 commented on apps/swifty-bank/public/img/agreement/Symbol_Agree.webp
피그마에서 다운로드한 PNG 사이즈가 작아서 크기를 키우면 깨지는 것 같아서 크기를 키워서 다운받았습니다. 
이후 무료 변환사이트에서 WEBP로 변환한 파일을 사용했는데, 데스크탑 뷰에서는 크기가 깨지지만, 휴대폰 크기로 보았을 때, 크기가 깨지지 않는 것 같은데, 그래도 이미지를 교체해볼까요?

2024-02-13 05:21 UTC, kd02109 commented on apps/swifty-bank/app/agreement/_component/agreementBtn.css.ts
> +};
전 전부 export로 처리했는데, 어떻게 처리하는게 좋을까요?

2024-02-13 05:24 UTC, kd02109 commented on apps/swifty-bank/public/img/agreement/Symbol_Agree.webp
휴대폰 화면에서도 이미지 화질이 깨지네요 다시 손보겠습니다!

2024-02-13 05:26 UTC, DoctorK4 commented on apps/swifty-bank/app/agreement/_component/agreementBtn.css.ts
> +};
저는 맨아래
`export default styles;`
로 통일하면 좋을 것 같습니다.

2024-02-13 05:30 UTC, kd02109 commented on apps/swifty-bank/app/agreement/_component/agreementBtn.css.ts
> +};
ui쪽 css.ts 파일모두 export default로 통일하셨네요!
그럼 저도 해당 방법으로 통일하겠습니다

2024-02-13 05:33 UTC, kd02109 commented on apps/swifty-bank/app/agreement/detail/page.tsx
해당 부분은 저는 정상적으로 동작을 해서 살펴보도록 하겠습니다. https://github.com/vanilla-extract-css/vanilla-extract/issues/1043 해당 이슈를 참고하면 module 방식과 연관이 있는 것 같은데, 저는 에러가 구현이 안 되서 해결 여부를 확인할 수가 없네요.. ㅜㅜ

2024-02-15 08:04 UTC, merged