Scrum 86 fe agree page/kd02109
ToyVallet/swifty-bank-frontend pull request #31
Opened 2024-02-19 11:49 UTC by kd02109

### What is this PR?
-  Bottom Sheet와 연동했습니다. 
---
### What has changed?
-  CheckBox Component를 만들었습니다. 
     해당 컴포넌트의 prop은 @swfitry/hook의 CheckBoxProp을 통해 확인할 수 있습니다. 
     사용 방법은 다음과 같이 사용할 수 있습니다.

```tsx
"use client";

import { Button, CheckBox } from "@swifty/ui";
import { HTMLAttributes } from "react";
import { useRouter } from "next/navigation";
import styles from "./checkboxForm.css";
import { useCheckBox } from "@swifty/hooks";

interface Button extends HTMLAttributes<HTMLButtonElement> {}

interface Prop {
  onClose: Button["onClick"];
}

export default function CheckboxForm({ onClose }: Prop) {
  const router = useRouter();
  const { terms, handleChange } = useCheckBox([
    {
      labelContent: "[필수] 서비스 이용약과 동의",
      isCheck: false,
      optional: false,
      isDetail: true,
      detailInfoType: "service",
    },
    {
      labelContent: "[필수] 개인정보 처리방침 동의",
      isCheck: false,
      optional: false,
      isDetail: true,
      detailInfoType: "personalInfo",
    },
    {
      labelContent: "[선택] 프로모션 등 안내 동의",
      isCheck: false,
      optional: true,
      isDetail: true,
      detailInfoType: "promotion",
    },
  ]);
 // 생략

  return (
    <section className={styles.container}>
      <div>
        {terms.map((term, idx) => (
          <CheckBox
            key={idx}
            {...term}
            id={`${idx}`}
            onChange={() => handleChange(term.isCheck, idx)}
          />
        ))}
      </div>
      <div className={styles.buttonSection}>
        <Button onClick={onClick}>동의하기</Button>
        <Button onClick={onClose} className={styles.closeButton}>
          닫기
        </Button>
      </div>
    </section>
  );
}
```

`isDetail` 과 `detailInfoType`은 CheckBox의 오른쪽 화살표 버튼 렌더링과 해당 버튼을 클릭할 경우 렌더링 되는 페이지의 내용을 결정합니다. 

현재 피그마에 있는 상세 약관 페이지는 개인정보 처리방침 만 있기 때문에, 우선 해당 내용으로 정리를 했습니다. 

따라서 Detail을 이제는 router로 관리하지 않고 컴포넌트로 관리하고 있습니다. 해당 컴포넌트를 CheckBox와 별도로 사용하는 경우는 없다고 판단하여 ui/src/checkbox/detail에 코드를 작성하여 관리하고 있습니다. 

- svg 관리를 코드로 접근하여 관리하는 것이 더 편리하다고 생각해서 ui/icon 에 svg를 컴포넌트로 관리하도록 만들었습니다. 

- 각 svg의 타입을 확장하거나 prop을 변경해야 하는 경우가 필요하다 판단하여 type.ts에서 svg icon과 관련된 type을 설정하였습니다. 
---
### A notice to reviewers...
- 
---
### Screen

https://github.com/ToyVallet/swifty-frontend/assets/57277708/fd81b138-c33d-441d-827e-2f81d6c56b99

2024-02-21 09:39 UTC, DoctorK4 approved these changes

2024-02-21 09:47 UTC, DoctorK4 reviewed
Review 코멘트 달다가 실수로 Approve했네요. 추가하고 다시 상태 변경하겠습니다.

2024-02-21 12:48 UTC, DoctorK4 approved these changes
test 코드까지

2024-02-21 12:48 UTC, DoctorK4 commented on apps/swifty-bank/app/signup/_component/checkbox-form/CheckboxForm.tsx
> +      labelContent: "[필수] 서비스 이용약과 동의",
'이용약과' 오타 있습니다

2024-02-21 12:48 UTC, DoctorK4 commented on apps/swifty-bank/app/signup/_component/checkbox-form/CheckboxForm.tsx
> +        <Button onClick={onClick}>동의하기</Button>
Button 컴포넌트를 새 디자인으로 적용하고 나면, 필수약관 체크 여부에 따라 동의하기 버튼이 "inactive"에서 "active"로 될 수 있게끔 동적으로 렌더링되게끔하면 더 좋은 사용자 경험을 줄 것 같습니다.

2024-02-21 12:48 UTC, DoctorK4 commented on packages/ui/src/checkbox/detail/detail-type.ts
> +export const termsOfDeatils: TermsOfDetail[] = [
식별자명에 오타있습니다.

2024-02-21 12:48 UTC, DoctorK4 commented on apps/swifty-bank/app/signup/_component/checkbox-form/CheckboxForm.tsx
크롬 개발자도구로 디버깅해봤을 때, 체크표시 이미지만을 클릭했을 때는 체크상태 변경이 되지 않는 것으로 보여집니다. 리팩토링 시 이부분을 수정한다면 더 좋을 것 같습니다.

2024-02-21 12:48 UTC, DoctorK4 commented on packages/ui/src/checkbox/index.tsx
> +        )}
createPortal을 통해 Detail 페이지를 부드럽게 잘 띄워주신 것 같습니다.

2024-02-21 12:48 UTC, DoctorK4 commented on packages/hooks/src/useCheckBox.ts
> +  const handleChange = useCallback((isCheck: boolean, id: number) => {
여기의 `handleChange` 도 이벤트를 인자로 받지 않으니 `onChange`가 되어야할까요?

2024-02-21 12:48 UTC, DoctorK4 commented on packages/hooks/src/useCheckBox.test.ts
테스트 항목이 무엇인지 상세하게 잘 적어주셔서 테스트 코드를 이해하는데 도움이 되었습니다.

2024-02-22 07:11 UTC, kd02109 commented on packages/ui/src/checkbox/detail/detail-type.ts
> +export const termsOfDeatils: TermsOfDetail[] = [
감사합니다! 수정했습니다!

2024-02-22 07:12 UTC, kd02109 commented on apps/swifty-bank/app/signup/_component/checkbox-form/CheckboxForm.tsx
> +      labelContent: "[필수] 서비스 이용약과 동의",
수정했습니다!

2024-02-22 07:12 UTC, kd02109 commented on apps/swifty-bank/app/signup/_component/checkbox-form/CheckboxForm.tsx
해당 부분 수정했습니다. 놓친 버그를 알려주셔서 감사합니다!

2024-02-22 07:12 UTC, kd02109 commented on packages/hooks/src/useCheckBox.ts
> +  const handleChange = useCallback((isCheck: boolean, id: number) => {
좋은 읜견입니다. 해당 부분도 수정했습니다.

2024-02-22 08:10 UTC, ho991217 requested changes
수고하셨습니다! 몇 가지 적어봤는데 확인해보시고 나누고 싶은 의견 있다면 편하게 말씀해주세요!

2024-02-22 08:10 UTC, ho991217 commented on apps/swifty-bank/app/_constant/path.ts
> +export const path = Object.seal({
`Object.seal()`은 객체 속성의 추가나 제거 등은 막아줄 수 있지만, 값의 변경은 막을 수 없습니다.
path 정의같은 경우 런타임에서의 변경 등이 일어나지 않기 떄문에,
리터럴 타입 선언이 가능한 `as const`를 활용하는 것은 어떨까요?

2024-02-22 08:10 UTC, ho991217 commented on packages/ui/src/icon/CheckIcon.tsx
> +      className={clsx(props.className)}
여기서 clsx를 사용해주신 이유가 뭔가요?

2024-02-22 08:10 UTC, ho991217 commented on packages/ui/src/icon/RightIcon.tsx
svg는 컴포넌트로 import해오는 방법이 있습니다. 현재 특별한 기능이 있는게 아니라, svg의 속성을 그대로 내려주고 있는데요. 이런경우 실제 사용하는 곳에서 svg파일을 바로 리액트 컴포넌트로 사용해주면 됩니다.

2024-02-22 08:10 UTC, ho991217 commented on packages/ui/src/icon/CheckIcon.tsx
이 부분도 굳이 컴포넌트로 분리해야하는지 궁금합니다.

2024-02-22 08:10 UTC, ho991217 commented on packages/ui/src/checkbox/detail/index.tsx
> +interface Button extends HTMLAttributes<HTMLButtonElement> {}
이 친구는 `HTMLAttributes<HTMLButtonElement>`에서 아무 속성도 추가하거나 변경하지 않는데요.
```suggestion
type Button= HTMLAttributes<HTMLButtonElement>;
```
이 더 적절한 표현 아닐까요?

2024-02-22 08:10 UTC, ho991217 commented on packages/ui/src/checkbox/detail/index.tsx
> +  const data = termsOfDeatils.filter(({ type }) => type === detailInfoType!);
이렇게 작성하면 `Detail` 컴포넌트가 리랜더될 때마다 filter 동작이 일어날 것같습니다.
`useEffect` 훅을 활용하거나 필터링을 거친 값을 내려주는 것을 어떨까요?

2024-02-22 08:10 UTC, ho991217 commented on packages/ui/src/checkbox/detail/index.tsx
> +    <AnimatePresence>
unmount되는 요소가 없어보입니다.
여기서 AnimatePresence를 사용한 이유가 뭔가요?

2024-02-22 08:10 UTC, ho991217 commented on packages/ui/src/checkbox/detail/index.tsx
> +  const data = termsOfDeatils.filter(({ type }) => type === detailInfoType!);
또한, `data`라는 단순한 이름보다 어떤 데이터를 나타내는지 명확히 나타내어주면 좋을 것 같습니다!

2024-02-22 08:10 UTC, ho991217 commented on packages/hooks/src/type/type.ts
> +}
이런 요소는 다른 서비스에서 공통으로 활용하기 어렵다고 생각합니다.
`ui`나 `hook`을 모노레포 별도의 프로젝트로 관리하는 이유를 생각해봤을 때, 이 부분은 실제로 활용하는 곳에서만 정의되어야할 것 같습니다.

2024-02-22 08:10 UTC, ho991217 commented on packages/hooks/src/type/type.ts
> +  detailInfoType?: TypeOfDetailInfo;
이 부분 같은 경우에도 특정 프로젝트에 국한된 필드 같아요.
일반적인 체크박스를 생각했을때는 어떤 프롭들이 필요한지 고민해서 최소한으로 사용해야할 것 같습니다.

2024-02-22 08:10 UTC, ho991217 commented on packages/ui/src/checkbox/index.tsx
> +interface Prop extends HTMLAttributes<HTMLDivElement>, CheckBoxProp {}
이 부분도 마찬가지로 단순 `extends`만 해주고 있습니다.
type을 이용한 방법이나, 또는 Prop을 아예 만들지 않고 진행하는 방법도 있겠네요!

2024-02-22 08:10 UTC, ho991217 commented on packages/ui/src/checkbox/index.tsx
> +  id,
id를 지정해주지 않고도 label과 input을 연결해주는 방법이 있으면 더 좋을 것 같습니다!
(useId 훅이 있어요!)

2024-02-22 08:10 UTC, ho991217 commented on apps/swifty-bank/app/signup/_component/agreement-button/AgreementButton.tsx
> +        expandTo="full"
<img width="511" alt="스크린샷 2024-02-22 13 45 26" src="https://github.com/ToyVallet/swifty-frontend/assets/84632077/7fce065a-693d-4db9-85b1-98c8dda0557d">

비율이 이상한 것 같습니다...!

2024-02-22 08:10 UTC, ho991217 commented on packages/ui/src/checkbox/detail/detail-type.ts
> +export const termsOfDeatils: TermsOfDetail[] = [
`[필수]`나 `[선택]`같은 레이블은 `optional` property에 따라 자동으로 들어가게끔 설정하면 더 좋겠네요!

2024-02-22 08:10 UTC, ho991217 commented on packages/ui/src/checkbox/detail/index.tsx
> +              {data[0]?.list.map((detailTerm) => (
`data[0]`의 의미가 명확하지 않은 것 같아요

2024-02-22 08:10 UTC, ho991217 commented on packages/ui/src/checkbox/detail/motion.ts
> +};
close는 작동하지 않는 것 같네요

2024-02-22 08:10 UTC, ho991217 commented on packages/ui/src/checkbox/index.tsx
> +  };
여기서 함수명은 열리거나 닫혔을 때의 콜백으로 적합해보이는데요,
실제로 하는 동작은 열거나 닫는 동작으로 보입니다!
`onOpen` 대신 `open`을, `onClose`대신 `close`를 사용하는 것은 어떻게 생각하세요?

2024-02-22 08:10 UTC, ho991217 commented on packages/hooks/src/useCheckBox.ts
> +    cloneTerms[id]!.isCheck = !isCheck;
non-assertion 연산자 대신 type guard를 활용하거나 nullish coalescing를 활용하는 편이 권장되는 것으로 알고있습니다...!!

2024-02-22 08:10 UTC, ho991217 commented on packages/hooks/src/useCheckBox.ts
> +  const handleChange = useCallback((isCheck: boolean, id: number) => {
일반 함수를 사용해도 크게 성능상의 이슈가 없는 로직이라고 생각합니다.
이 커스텀훅은 한 화면에 한번 호출되는 데다가,
오히려 useCallback을 사용하면서 메모리낭비가 생길 수 있지 않을까요?

2024-02-22 08:10 UTC, ho991217 commented on apps/swifty-bank/app/signup/_component/checkbox-form/CheckboxForm.tsx
> +      alert("모든 사항을 동의해주세요!");
이 부분은 추후에 다른 로직으로 바뀌어야겠네요!

2024-02-22 08:10 UTC, ho991217 commented on apps/swifty-bank/app/signup/_component/checkbox-form/CheckboxForm.tsx
> +    }
```suggestion
    const isAllTermChecked = terms.every(({ isCheck, optional }) =>  optional || isCheck);
    
    if (!isAllTermChecked) {
      alert("모든 사항을 동의해주세요!");
      return;
    }
```
로 간략하게 쓸 수 있겠네요!

2024-02-22 08:10 UTC, ho991217 commented on apps/swifty-bank/app/signup/_component/agreement-button/AgreementButton.tsx
> +        <CheckboxForm onClose={close} />
모든 항목이 체크되지 않으면 버튼이 비활성화되면 좋을 것 같습니다...!

2024-02-23 03:26 UTC, kd02109 commented on packages/ui/src/icon/CheckIcon.tsx
> +      className={clsx(props.className)}
이부분은 필요가 없을 것 같아요!

2024-02-23 03:58 UTC, kd02109 commented on packages/ui/src/icon/RightIcon.tsx
svg 아이콘을 일괄적으로 관리하면 좋을 것 같아서 컴포넌트로 함께 만들었는데, svg 속성을 그대로 내려준다면, svg 파일로 관리하는게 더 좋다고 보시나요?

2024-02-23 04:00 UTC, kd02109 commented on packages/ui/src/checkbox/detail/index.tsx
> +interface Button extends HTMLAttributes<HTMLButtonElement> {}
다른 곳에서 타입 관리를 interface로 해서 통일하기 위해 interface를 사용했습니다. type과 interface를 언제 사용할지 정해둔 규칙이 따로 있을까요?

2024-02-23 04:11 UTC, kd02109 commented on packages/ui/src/checkbox/detail/index.tsx
> +  const data = termsOfDeatils.filter(({ type }) => type === detailInfoType!);
전 filter 동작이 리렌더링 할 때마다 동작하는 것이 크게 문제가 될 것 같지 않습니다.! 배열의 길이가 크지 않고, 컴포넌트 자체의 크기도 크지 않기에 큰 문제가 될 것 같지 않다고 생각했습니다! 
useEffect로 data를 관리하면 불필요한 state와 리렌더링이 필요하기에 적합하지 않다고 생각했습니다.!

2024-02-23 04:21 UTC, kd02109 commented on packages/hooks/src/type/type.ts
> +  detailInfoType?: TypeOfDetailInfo;
현재 checkbox는 디테일 페이지를 보여주는 기능과 엮어서 공통 UI로 만들었기에 위와 같은 prop이 필요해졌습니다. 이를 한번더 나누어서 checkbox는 checkbox로만 역할을 하고, 상세 페이지를 보여주는 기능이 필요한 checkbox는 공통 ui의 checkbox를 확장해서 사용하는 방법으로 확장하는게 좋을까요?

2024-02-23 04:39 UTC, kd02109 commented on apps/swifty-bank/app/signup/_component/agreement-button/AgreementButton.tsx
> +        expandTo="full"
이 부분은 버튼 컴포넌트 크기를 수정하면서 해결할 수 있을 것 같습니다! .

2024-02-23 14:36 UTC, ho991217 commented on apps/swifty-bank/app/signup/_component/agreement-button/AgreementButton.tsx
> +        expandTo="full"
버튼 말고 하단 영역이 과도하게 큰 것 같아요
1/3로 설정해주셔서 그런 것 같습니다

2024-02-23 14:38 UTC, ho991217 commented on packages/ui/src/icon/RightIcon.tsx
넵 저는 1개의 파일로 할 수 있는 일을 2개의 파일로 처리하는 것이라고 생각합니다!

2024-02-23 14:39 UTC, ho991217 commented on packages/ui/src/checkbox/detail/index.tsx
> +  const data = termsOfDeatils.filter(({ type }) => type === detailInfoType!);
필요한 데이터만 prop으로 넘겨받는 것도 나쁘지 않은 생각이라고 봅니다...!!

2024-02-26 10:22 UTC, kd02109 commented
- react hook form을 활용하는 방법으로 변경했습니다.
- 이에 따라 기존에 만든 useCheckBox 등의 컴포넌트가 필요없게 되어 이를 수정했습니다.

2024-02-27 10:20 UTC, DoctorK4 commented on apps/swifty-bank/app/signup/_component/agreement-button/AgreementButton.tsx
https://github.com/ToyVallet/swifty-frontend/assets/68728192/b3b4fef5-4a22-4f4f-ba98-d21abf2df40f

디버깅 해보니 체크 이미지를 클릭했을 때는 버튼 상태가 연동이 안되고 본문 글을 클릭했을때만 연동이 됩니다!

2024-02-27 10:22 UTC, kd02109 commented on apps/swifty-bank/app/signup/_component/agreement-button/AgreementButton.tsx
해당 부분을 처리했는데, 분명 가능한걸로 확인했는데... 다시 확인해보겠습니다.. ㅜㅜ

2024-02-27 10:50 UTC, kd02109 commented on apps/swifty-bank/app/signup/_component/agreement-button/AgreementButton.tsx
해당 문제 해결했습니다!

2024-02-27 10:56 UTC, kd02109 commented
Check 공통 UI에서 아이콘을 사용하는 문제로 인해 ref 값과 동기화하는 로직이 추가로 필요했습니다!  이를 위해 react-hook-form의 unique key값과 setValue 함수를 인자로 넘겨 주는 방식으로 만들었습니다.

Detail에 필요한 데이터를 상위 컴포넌트에서 필터링해서 넘겨주는 방식도 생각을 해보았는데, 저는 해당 방식이 어디서 데이터를 넘겨줄지도 정해야 하고, 해당 데이터를 필터하기 위한 key값도 넘겨주어야 하는점이 오히려 DX에 좋지 않다고 생각해서 기존의 방식을 사용하도록 수정했습니다.

2024-02-27 14:34 UTC, ho991217 approved these changes
LGTM ^^

2024-02-28 00:11 UTC, merged