Toast/kd02109
ToyVallet/swifty-bank-frontend pull request #42
Opened 2024-03-04 05:37 UTC by kd02109

### What is this PR?
- toast 컴포넌트 생성
- 단일 toast 구조로 생성
-  close: #35 
---
### What has changed?
- 위치 값을 고려하지 않아도 되기에 항상 하단 중앙에서 나오도록 수정
- 고정 시간은 1초로 설정, 시간 설정은 초단위로 작성
- type과 toast의 content만 prop으로 넘겨 줍니다.
---
### A notice to reviewers...
- 
---
### Screen

https://github.com/ToyVallet/swifty-frontend/assets/57277708/8328c8f2-e329-407c-982e-ce849c8f4a36

2024-03-04 09:09 UTC, DoctorK4 approved these changes
전반적으로 좋은 것 같습니다. 고생하셨습니다!

2024-03-04 09:09 UTC, DoctorK4 commented on packages/ui/src/toast/index.tsx
> +              type === "success" && styles.sucessToast,
이번에 만드신 것은 Success와 Error 타입만 있지만, 아래 이미지와 같이 토스트 타입이 추가되어야하는 경우에는 조금 더 효율적인 방법을 고민해야할 수도 있을 것 같습니다.
<img width="188" alt="Screenshot 2024-03-04 at 6 04 44 PM" src="https://github.com/ToyVallet/swifty-frontend/assets/68728192/804f097e-fac8-497e-b680-240261921681">

2024-03-04 10:02 UTC, kd02109 commented on packages/ui/src/toast/index.tsx
> +              type === "success" && styles.sucessToast,
지금 당장 success, error 이외에 별도의 type이 필요한 경우를 찾을 수 없어서, 우선 두가지만 포함을 했습니다.

2024-03-04 12:45 UTC, ho991217 requested changes
고생하셨습니다..!

2024-03-04 12:45 UTC, ho991217 commented on apps/swifty-bank/app/page.tsx
> +      <Toast type="sucess" content="test" />
children 형태로 넘겨주는 것은 어떻게 생각하시나요? string 형태의 메시지 말도 전달 할 수 있게 되니 유연성이 더 높아질 것 같습니다...!

2024-03-04 12:45 UTC, ho991217 commented on packages/ui/src/toast/index.tsx
> +const ANIMATION_DURATION = 500;
상수로 따로 빼 주신것 좋네요!

2024-03-04 12:45 UTC, ho991217 commented on packages/ui/src/toast/index.tsx
> +  };
다른 파일들과 디자인패턴에 맞게 motion.ts로 빼 주는 것도 좋을 것 같습니다...!

2024-03-04 12:45 UTC, ho991217 commented on packages/ui/src/toast/index.tsx
> +            variants={toastVariants}
애니메이션이 이쁘게 들어간 것 같습니다...!

2024-03-04 12:45 UTC, ho991217 commented on packages/ui/src/toast/toast.css.ts
> +});
ve의 composition을 활용하시면 스타일을 상속할 수 있습니다!
```suggestion
const sucessToast = style([toast, {
  backgroundColor: "#E8E5FF",
}]);

const errorToast = style([toast, {
  backgroundColor: "rgba(254,82,92,0.15)",
}]);
```

2024-03-04 12:45 UTC, ho991217 commented on packages/ui/src/toast/toast.css.ts
> +const sucessToast = style({
오타가 있네요!
```suggestion
const successToast = style({
```

2024-03-04 12:45 UTC, ho991217 commented on packages/ui/src/toast/toast.css.ts
> +  borderRadius: 20,
좌우가 90%로 고정이고, 상/하단 패딩값 자체도 조금 크기 때문에, 토스트 컴포넌트 자체가 조금 커 보입니다.
좌우는 컨텐츠 사이즈에 맞게 늘어나고, 패딩값도 조금 줄이면 좋지 않을까요?

2024-03-05 04:14 UTC, kd02109 commented on packages/ui/src/toast/toast.css.ts
> +  borderRadius: 20,
이부분은 피그마 디자인에 맞춰서 크기를 맞추었는데, width 크기는 text에 맞추어 유동적으로 변경되고, 
heigth padding 값은 줄여서 toast 크기를 줄이는게 좋을까요?

2024-03-05 04:31 UTC, kd02109 commented
- 코드 리뷰에 맞추어서 toast 구조를 수정했습니다. 
1. 고정 toast 타입으로 sucess로 할당했습니다. 
2. toast content를 children prop으로 변경했습니다. string 혹은 component를 받을 수 있도록 변경했습니다.
3. framer-motion의 variants 값을 별도 파일로 구분했습니다.
4. toast 스타일을 수정했습니다.
```ts
const toast = style({
  padding: `${vars.space[1]} ${vars.space[3]}`,
  textAlign: "center",
  fontSize: 16,
  color: vars.color.text,
  boxShadow: "0px 4px 3px rgba(0,0,0,0.25)",
  borderRadius: 20,
});

const successToast = style([
  toast,
  {
    backgroundColor: "#E8E5FF",
  },
]);

const errorToast = style([
  toast,
  {
    backgroundColor: "rgba(254,82,92,0.15)",
  },
]);

const styles = { successToast, errorToast, container };
```

2024-03-05 09:59 UTC, ho991217 approved these changes

2024-03-05 09:59 UTC, merged